image: Visual Studio 2022

build:
  verbosity: detailed

artifacts:
  - path: /src/**/*.nupkg

build_script:
  - cmd: dotnet restore --locked-mode
  - cmd: dotnet build -c Release --no-restore

test_script:
  - cmd: dotnet test -c Release --no-build -- Expecto.fail-on-focused-tests=true

deploy:
  - provider: NuGet
    api_key:
      secure: xwsC/mXTfVThZqYP5zzQIMZykH6OHw0H3/jL+bj3L00i8jvHxXuFA3YMcUCqhOxL
