name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install .NET SDK 5.0.103
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103

    - name: Restore
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release
